#import = [
	# "~/.config/alacritty/themes/chicago95.toml"
#]

[font]
size = 13
[font.bold]
family = "Mononoki Nerd Font"
[font.bold_italic]
family = "Mononoki Nerd Font"
[font.italic]
family = "Mononoki Nerd Font"
[font.normal]
family = "Mononoki Nerd Font"

[window]
opacity = 0.95

[window.padding]
x = 10
y = 10
